### ISSUE TITLE
Consider using BinaryBuilder and BInaryProvider

### ISSUE THREAD

**Issue by rofinn** [IQVIA-ML/LightGBM.jl#112]
The current `deps/build.jl` script doesn't really work for me as it assumes I already have the `lib_lightgbm.dylib` dependencies already installed. Since `Libdl.find_library` doesn't provide any details on why the file doesn't work, you need to call `dlopen` on the downloaded file and install the system dependencies. BinaryBuilder provides a mechanism for specifying these dependencies and BinaryProvider provides a standardized interface for installing these dependencies on various platforms.

**Comment by yalwan-sage** [comment]
Hi @rofinn the only dependency is libomp -- did you have a trouble obtaining this?

**Comment by rofinn** [comment]
No, I can install it with brew on my local system. It’d be nice if we didn’t need to have it as a separate setup process though.

**Comment by rofinn** [comment]
If I find some time over the next week or two, I'll make a PR with that change.

**Comment by yaxxie** [comment]
See also: https://github.com/IQVIA-ML/LightGBM.jl/issues/37#issuecomment-613326087

A PR would be well received -- when doing so, it would be good to consider how to make this opt out.

**Comment by kainkad** [comment]
Hi @rofinn just to let you know I'm closing this issue as the LightGBM version >=v0.7.0 is now using BinaryBuilder so you shouldn't need to install any dependencies locally. BinaryProvider repo has been archived.
