### ISSUE TITLE
Feature Request: LightGBM Ranking

### ISSUE THREAD

**Issue by WZimmerman83** [IQVIA-ML/LightGBM.jl#118]
Hi, are there plans to add ranking to this package (LightGBM Ranker)? Currently the only ways to get ranking is going PyCall method for Catboost or convert all variables to numeric for XGBoost (this is a nightmare for large/wide datasets).

having a 100% Julia solution would be awesome.

**Comment by yaxxie** [comment]
Hi @WZimmerman83, thanks for the issue!

Very old versions of this package actually supported this. I'm not sure why it was removed.

With that said, I'll take a look at what's needed to add it in.

**Comment by rbeeli** [comment]
+1
