### ISSUE TITLE
Automate the selection of num_class in classifiers for MLJ implementation

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/LightGBM.jl#27]
An MLJ user will not expect this error:

```julia
julia> X, y = @load_iris;

julia> model = LightGBM.MLJInterface.LGBMClassifier();

julia> fit!(machine(model, X, y))
[ Info: Training Machine{LGBMClassifier} @ 4…61.
[LightGBM] [Fatal] Number of classes should be specified and greater than 1 for multiclass training
ERROR: call to LightGBM's LGBM_BoosterCreate failed: Number of classes should be specified and greater than 1 for multiclass training
Stacktrace:
 [1] error(::String, ::String, ::String, ::String) at ./error.jl:42
 [2] LGBM_BoosterCreate(::LightGBM.Dataset, ::String) at 
...
```

Because of MLJ's insistence on categorical arrays for categorical data, you have the information you need to automatically determine `num_class` from the target `y` (even when not all classes are "observed" in `y`). Given any element `e` of `y` (say `e = y[1]`) this is given by `MLJModelInterface.classes(e) |> length` or you can also use `length(levels(y))` (but I recommend the first option).

For an example, see the [XGBoost wrap](https://github.com/alan-turing-institute/MLJModels.jl/blob/6de5f22db53fd149faa7bc29315c1c0a94c78821/src/XGBoost.jl#L588)

**Comment by ablaom** [comment]
Also, why do you need a separate Binary model? You can dispatch the appropriate classifier based on the number of classes you find in the data because the data always knows *all* the classes. 

Again, see how this is handled in the [XGBoost wrap](https://github.com/alan-turing-institute/MLJModels.jl/blob/6de5f22db53fd149faa7bc29315c1c0a94c78821/src/XGBoost.jl#L588) where a single classification model handles any number of classes without user input. 

Generally speaking, the LightGBM and XGBoost API are pretty close, so the above referenced MLJ wrap of XGBoost should be quite helpful. You also have the [EvoTrees](https://github.com/Evovest/EvoTrees.jl) example (which includes implementation of `update` for later).

**Comment by yalwan-iqvia** [comment]
I take the point on binary vs multiclass, however right now its a bit of a tangle and its related to objective pinning, which needs to get sorted as part of enabling the user to select their optimisation objective. So, for now, I'd rather leave it as is. However a num_classes fix is coming up

**Comment by yalwan-iqvia** [comment]
https://github.com/IQVIA-ML/LightGBM.jl/pull/31, partially, and #30 for the remainder

**Comment by ablaom** [comment]
I think this needs to be sorted before registration, and I'd rather do my testing after these issues are resolved (especially, as I have to hack the installation each time).  I don't think it is acceptable to provide a model (Binary) and then later take it away. 

The objective function choice is tied to the scitype of the target, ie on the particular model, in the MLJ implementation. I do think you might find the XGBoost wrap helpful in seeing how to handle this. The XGBoost and LightGBM API are very close (I have wrapped both previously). In summary, this is what is done for XGBoost:

**Regressor** (Deterministic, target elscitype=Continuous)
User can select any objective but warning is issued if an objective suitable to other model is selected (see [here](https://github.com/alan-turing-institute/MLJModels.jl/issues/96) as to why we allow we only issue a warning and not error):

```julia
function MMI.clean!(model::XGBoostRegressor)
    warning = ""
    if model.objective == "count:poisson"
        warning *= "Your `objective` suggests prediction of a "*
        "`Count` variable.\n You may want to consider XGBoostCount instead. "
    elseif model.objective in ["reg:logistic", "binary:logistic",
                               "binary:logitraw", "binary:hinge",
                               "multi:softmax", "multi:softprob"]
        warning *="Your `objective` suggests prediction of a "*
        "`Finite` variable.\n You may want to consider XGBoostClassifier "*
        "instead. "
    end
    return warning
end
```

**Classifier** (Probabilistic, target elscitype <: Finite)
objective is automatically set (to "logloss" or "mlogloss" depending on classes = 2 or > 2):

```julia
function MMI.clean!(model::XGBoostClassifier)
    warning = ""
    if(!(model.objective =="automatic"))
            warning *="Changing objective to \"automatic\", the only supported value. "
            model.objective="automatic"
    end
    return warning
end
```

**Count** (Deterministic, target elscitype = Count)
`objective` fixed to `count:possion`:

```julia
function MMI.clean!(model::XGBoostCount)
    warning = ""
    if(!(model.objective in ["count:poisson"]))
        warning *= "Changing objective to \"poisson\", "*
                       "the only supported value. "
        model.objective="poisson"
    end
    return warning
end
```

Perhaps you have some objection to the way this is handled here? Or you believe LightGBM presents some new challenges? Could you say more about what the roadblocks are here?

**Comment by yalwan-iqvia** [comment]
The fundamental issue is that the underlying estimator objects MLJ interface is using have fixed their objectives, so theres no way to pass it through currently. And while taking the time to deal with this one might as well remove the binary/multiclass distinction from the codebase entirely and allow user to specify their own objectives. This just represents a larger piece of work.

**Comment by ablaom** [comment]
Right. So you understand our requirements, agree they are reasonable, but to implement them will take some work?

**Comment by yalwan-iqvia** [comment]
Yep, but I've already started and actually think I can push something out later today

**Comment by yalwan-iqvia** [comment]
#31 addresses
