### ISSUE TITLE
Remove need for Mac users to separately install libomp

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/LightGBM.jl#37]
I'm not an expert on this but it seems others have figured this out (eg, XGBoost.jl). A good resource (although get's a lot of traffic) would be the julia slack channel #binarybuilder

**Comment by yalwan-iqvia** [comment]
I'll take a look as time allows (I don't currently consider this high priority)  but a lot of it will depend on what the method used is. 

For example, if it is about statically linking libomp or even shipping a copy, these can be pretty big no-go's as they can cause hard to troubleshoot library clashes, and at a fundamental level `brew install libomp` isn't a big thing to ask users to do -- even with a batteries included approach there is only so far one should go, and pre-requisites are a valid thing.

**Comment by kainkad** [comment]
Closing the issue as LightGBM >=v0.7.0 is using BinaryBuilder so there's no need to install libomp
