### ISSUE TITLE
MLJ Tests

### ISSUE THREAD

**Issue by yalwan-iqvia** [IQVIA-ML/LightGBM.jl#40]
I'm not immediately able to explain the PipeError problem. If this persists and you believe it's an MLJ issue, please post an issue.

Instead, you could do:

```julia
using Test
using MLJBase
import LightGBM

X, y = @load_boston;
model = LightGBM.MLJInterface.LGBMRegressor()
yhat = machine(model, X, y) |> fit! |> predict;
scitype(yhat) == AbstractVector{Continuous}
@test rms(yhat, y) < 6  # or do proper out-of-sample test 

X, y = @load_iris;
model = LightGBM.MLJInterface.LGBMClassifier()
yhat = machine(model, X, y) |> fit! |> predict;
@test scitype(mode.(yhat)) <: AbstractVector{Multiclass{3}}
@test mean(cross_entropy(yhat, y)) < 0.6  # or do proper out-of-sample test 
```

Happy for you to close this issue.

_Originally posted by @ablaom in https://github.com/IQVIA-ML/LightGBM.jl/issues/32#issuecomment-611812596_

^ Above snippet is for MLJ Integration test. Add to code

**Comment by yalwan-iqvia** [comment]
Closed by #49 

(but revisit at some point when machine  takes verbosity argument to reduce output vomit)

**Comment by ablaom** [comment]
> (but revisit at some point when machine takes verbosity argument to reduce output vomit)

Not sure this is what your mean here. But FYI: you can't give the `machine` constructor verbosity argument but you can give a verbosity argument to `fit!`, as in `fit!(mach, verbosity=0)`.

**Comment by yalwan-iqvia** [comment]
Huh thanks, let me try this out
