### ISSUE TITLE
Readme Error

### ISSUE THREAD

**Issue by azev77** [IQVIA-ML/LightGBM.jl#42]
Hi, 
the example in the Readme works until 
`fit!(estimator, X_train, y_train, (X_test, y_test))`
It says: 
```Julia
UndefVarError: fit! not defined
top-level scope at untitled-b3982c07ed1d8574076c6c731682b5e4:41
```

**Comment by yalwan-iqvia** [comment]
Thanks for taking the time to report this.

Actually the README is right, and the code has an error. When I did a latest piece of work I also decided that `fit` should be `fit!` as it mutates its arg, but I apparently forgot to update the export, and these fail silently. Will prepare a release patch. In the meantime, you should find that writing it out fully qualified , i.e. `LightGBM.fit!()` should work.

I apologise for the inconvenience.

**Comment by yalwan-iqvia** [comment]
@azev77 

Once this PR is merge, https://github.com/JuliaRegistries/General/pull/13002

LightGBM.jl 0.2.1 will be available, which should resolve this problem. Thanks for taking the time to report the issue. (please note there is also a small tweak in README.md)

**Comment by azev77** [comment]
It works now! thank you. 

Btw, how did you decide to set default values for the tuning parameters?
I think the current `min_data_in_leaf=100`
But in the [original pkg](https://github.com/microsoft/LightGBM/blob/eda4d644c7bd9be0454f0908a02fbc6c86a1166d/docs/Parameters.rst#min_data_in_leaf): `min_data_in_leaf=20`

**Comment by azev77** [comment]
Also is it possible to change the boosting type to "dart":
https://github.com/microsoft/LightGBM/blob/eda4d644c7bd9be0454f0908a02fbc6c86a1166d/docs/Parameters.rst#boosting

**Comment by yalwan-iqvia** [comment]
This package is forked from the wakakusa version as of around January, so it carries same "warts", so to speak. I hadn't noticed that some of the defaults inside the wrapper don't match the main library. I'll raise an issue for this and the boosting type and mention you in it.
