### ISSUE TITLE
Incorrect is_wrapper trait value for MLJ interface

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/LightGBM.jl#46]
The following should be changed to `false` in all your models. It is the default. 

I recently rebuilt (locally) the MLJ model registry and your models mysteriously vanished. The new behaviour may be because of something in MLJModel I "fixed" but `false` is indeed the correct value. 

The trait is `true` for meta-models, such as `TunedModel` that you don't want to appear in the registry.

**Comment by ablaom** [comment]
Sorry, I forgot the link:

https://github.com/IQVIA-ML/LightGBM.jl/blob/6e07ff1d2e2c8651e0c11986cf3a32ec6dd6918d/src/MLJInterface.jl#L240

**Comment by yalwan-iqvia** [comment]
Sorry I didn't respond sooner, for some reason I didn't get an email. Fix is incoming.

**Comment by yalwan-iqvia** [comment]
Sorry it took me so long to get to this:

https://github.com/JuliaRegistries/General/pull/14566

If it doesn't do what you need, please re-open.
