### ISSUE TITLE
Implement LGBM_BoosterUpdateOneIterCustom

### ISSUE THREAD

**Issue by yalwan-iqvia** [IQVIA-ML/LightGBM.jl#5]
https://github.com/IQVIA-ML/LightGBM.jl/blob/b5293367b451b9a8fcd78d055890a384bc8c2485/src/wrapper.jl#L356

We need  `LGBM_BoosterUpdateOneIterCustom` if we wish to support custom objectives.

https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterUpdateOneIterCustom

**Comment by yaxxie** [comment]
Closed by #114
