### ISSUE TITLE
Cleaner documentation

### ISSUE THREAD

**Issue by yalwan-iqvia** [IQVIA-ML/LightGBM.jl#54]
The README is pretty long and will only get longer.

Can we tidy this up by using a smaller collection of documents in /docs/ and Github pages?

**Comment by wakakusa** [comment]
Using Documenter, you can create function documentation from comments in the source code. First of all, why don't you try to remove the function's description from the README after you create the function's documentation?

**Comment by yalwan-iqvia** [comment]
Hi @wakakusa!

Do you mean that we should remove the stuff explicitly written out in the README.md if it is already present as a docstring?
I'm also happy if you would open a PR with example usage of Documenter.jl and how you think it could look.

**Comment by wakakusa** [comment]
Hi @yalwan-iqvia 
#67 New function documentation has been created and function descriptions have been removed from Readme.md.

**Comment by yalwan-iqvia** [comment]
Resolved by #67
