### ISSUE TITLE
Module files that import LightGBM fail to compile

### ISSUE THREAD

**Issue by msekino** [IQVIA-ML/LightGBM.jl#71]
I'd like to use LightGBM in a module file.
I made a project "Example" and wrote a following code in Example.jl
```
module Example
using LightGBM
end
```
`using Example` resulted in the following.
```
┌ Info: Precompiling Example [9e033b86-410e-4dd2-a032-f2c9367e52e7]
└ @ Base loading.jl:1278
ERROR: LoadError: InitError: Evaluation into the closed module `LightGBM` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `LightGBM` with `include` during precompilation - don't do this.
Stacktrace:
...
```

Temporarily, it is possible to avoid the error by putting `__precompile__(false)` to the beginning of the file, but it doesn't seem to be a very preferred solution.

**Comment by yalwan-iqvia** [comment]
Hi @msekino ! Thanks for taking the time to report this

After a quick bit of digging it seems it is due to this:

https://github.com/IQVIA-ML/LightGBM.jl/blob/47d9a878626ed5f2430a83fed21a5f3e72f47c1a/src/LightGBM.jl#L21

I'll have to figure out why I did it and then stop doing it without breaking it. I will keep you up to date with this. Hopefully the fix can make it soon.

**Comment by yalwan-iqvia** [comment]
```
WARNING: eval into closed module MLJModelInterface:
:Bool
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module MLJModelInterface:
:Bool
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module MLJModelInterface:
:Bool
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module MLJModelInterface:
:Bool
  ** incremental compilation may be fatally broken for this module **

```

I think I did it to stop this class of warnings appearing. However, it seems like its no consequence for me to remove this include from the init, which would fix the issue. I will go to MLJ project and see what I can do to suppress those warnings.

I will try to come with a fix soon.

**Comment by yalwan-iqvia** [comment]
@ablaom do you know what I might do in order to stop those warnings appearing?

**Comment by ablaom** [comment]
Yeah, I've also had problems using `eval`(and hence macros)  inside an `__init__` function (see https://github.com/alan-turing-institute/MLJModels.jl/issues/74). What's the reason for including the file `MLJInterface.jl` *post facto* ? If you move it out of `__init__` I expect the warnings will go away. 

Maybe this helps: https://github.com/JuliaLang/julia/issues/29059 .

**Comment by yalwan-iqvia** [comment]
Sorry, I was a little unclear. I was asking because it occurs when I move it out of `__init__`

**Comment by ablaom** [comment]
Oh, I see. This looks like a problem with MLJModelInterface.jl.

My guess is there is an issue with `metadata_pkg` and `metadata_model` methods, which have `eval` in them. Maybe something to do with use of `parentmodule`, but I'm not sure and not completely understanding why this has not come up with other interfaces. I will investigate. cc @tlienart 

Would be helpful to know if you get the warnings if you remove the module wrapping of the code in MLJModelInterface.jl.

If my suspicions are right, a solution for you might be to replace the calls to `metadata_pkg` and `metadata_model`  with explicit trait definitions. (Personally, I prefer this anyhow). See the attached screenshot, which is from https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Trait-declarations-1 

![Uploading Screen Shot 2020-10-14 at 8.07.09 AM.png…]()

**Comment by yalwan-iqvia** [comment]
I managed to find this:

https://discourse.julialang.org/t/use-of-eval-in-closed-module-and-incremental-compilation-may-be-broken/30028

Is it possible that is related?

**Comment by yalwan-iqvia** [comment]
https://github.com/alan-turing-institute/MLJModelInterface.jl/blob/master/src/model_def.jl#L70
This the possible culprit?

**Comment by ablaom** [comment]
Yes that's it. Good catch. This needs to be evaluated in the  module from where the @mlj_macro is called, which must according be passed to the function you point out as an argument. 

Working on a new release of MLJModelsInterface. Thanks for bringing this to my attention.

**Comment by ablaom** [comment]
@msekino When https://github.com/JuliaRegistries/General/pull/22970 is merged, would you be so kind as to update your project env and confirm that my fix resolves your issue?

**Comment by ablaom** [comment]
Oh sorry. @yalwan-iqvia will first need to move the include out of `__init__` for this to work.

**Comment by msekino** [comment]
@ablaom Yes, I'll be glad to try it!  Best regards.

**Comment by msekino** [comment]
@ablaom Thank you for your help!

I just updated as follows.
```
(@v1.5) pkg> up
   Updating registry at `C:\Users\msekino\.julia\registries\General`
  Installed MLJModelInterface ─ v0.3.6
  ...
Updating `C:\Users\msekino\.julia\environments\v1.5\Project.toml`
  ...
Updating `C:\Users\msekino\.julia\environments\v1.5\Manifest.toml`
  [e80e1ace] ↑ MLJModelInterface v0.3.5 ⇒ v0.3.6
  ...
```

I made a project "Example"
```
julia> using PkgTemplates
[ Info: Precompiling PkgTemplates [14b8a8f1-9102-5b29-a752-f990bacb7fe1]

julia> t = Template(user = "msekino")
  ...

julia> t("Example")
  ...
```

then, I wrote Example.jl
```
module Example
using LightGBM
end
```

However, `using Example` resulted in the following.
```
julia> using Example
[ Info: Precompiling Example [400a67cc-5385-4025-bc17-a97de4bd9e1e]
ERROR: LoadError: InitError: Evaluation into the closed module `LightGBM` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `LightGBM` with `include` during precompilation - don't do this.
Stacktrace:
 [1] include(::Function, ::Module, ::String) at .\Base.jl:380
 [2] include at .\Base.jl:368 [inlined]
 [3] include at C:\Users\msekino\.julia\packages\LightGBM\3uotD\src\LightGBM.jl:1 [inlined]
 [4] __init__() at C:\Users\msekino\.julia\packages\LightGBM\3uotD\src\LightGBM.jl:21
 [5] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
 [6] _require_from_serialized(::String) at .\loading.jl:749
 [7] _require(::Base.PkgId) at .\loading.jl:1040
 [8] require(::Base.PkgId) at .\loading.jl:928
 [9] require(::Module, ::Symbol) at .\loading.jl:923
 [10] include(::Function, ::Module, ::String) at .\Base.jl:380
 [11] include(::Module, ::String) at .\Base.jl:368
 [12] top-level scope at none:2
 [13] eval at .\boot.jl:331 [inlined]
 [14] eval(::Expr) at .\client.jl:467
 [15] top-level scope at .\none:3
during initialization of module LightGBM
in expression starting at D:\workspace\private\Julia\Example\src\Example.jl:3
ERROR: Failed to precompile Example [400a67cc-5385-4025-bc17-a97de4bd9e1e] to C:\Users\msekino\.julia\compiled\v1.5\Example\UxrAa_P2WnP.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1305
 [3] _require(::Base.PkgId) at .\loading.jl:1030
 [4] require(::Base.PkgId) at .\loading.jl:928
 [5] require(::Module, ::Symbol) at .\loading.jl:923
```

I'm not sure what caused it. And I'm sorry if I'm doing something wrong...

**Comment by yalwan-iqvia** [comment]
@msekino hey sorry for the confusion. What's going on here is that @ablaom has made a fix to an upstream project which I will test now and then make a release. So you'll need an updated version of LightGBM.jl (which I am working on now)

**Comment by yalwan-iqvia** [comment]
@ablaom I've done this but do you think there might be a better way?
https://github.com/IQVIA-ML/LightGBM.jl/pull/73/commits/58661c6b6851fd2d6d4c880f28e1142a7adebdb1

**Comment by yalwan-iqvia** [comment]
@msekino when this merge is complete https://github.com/JuliaRegistries/General/pull/22979

it should hopefully resolve your issue. You will need to make sure to update to LightGBM.jl >= 0.3.2

**Comment by msekino** [comment]
@yalwan-iqvia @ablaom
Now I was able to precompile the module without problems!
Thank you very much for the quick resolution!

**Comment by yalwan-iqvia** [comment]
Thanks for reporting and thanks Anthony for the super quick response 😄

**Comment by ablaom** [comment]
> @ablaom I've done this but do you think there might be a better way?
58661c6

Nope. That's the way to do it.
