### ISSUE TITLE
possible bug with MLJInterface

### ISSUE THREAD

**Issue by kainkad** [IQVIA-ML/LightGBM.jl#78]
While upgrading LightGBM to v.3.0.0 an issue has been found with one of the previously passing tests now failing: https://github.com/IQVIA-ML/LightGBM.jl/blob/master/test/mlj/binary_classifier.jl#L41 where we compare predictions for models fitted with and without weights. The issue has been troubleshooted and indicated a possible bug with the MLJInterface.
The below code shows that the issue wasn't with the LightGBM upgrade itself as the same test has passed after removing the MLJInterface and fitting and predicting directly with LightGBM:

```julia
using MLJBase
using Test
using Random: seed!

import CategoricalArrays
import LightGBM

N = 2
seed!(0)

X       = rand(1000, 3)
ycat    = string.(mod.(round.(Int, X[:, 1] * 10), N)) |> MLJBase.categorical
weights = Float64.(MLJBase.int(ycat)) # just use the 1's/2's directly as multipliers

y = MLJBase.int(ycat) .-1 # make plain Vector with categ. elements (actually not sure what this is doing)


train, test = MLJBase.partition(MLJBase.eachindex(y), 0.6) # prepare train and test data
X_train = MLJBase.selectrows(X, train)
y_train = y[train]
X_test = MLJBase.selectrows(X, test)


model = LightGBM.LGBMClassification(objective="binary", num_class=1, num_iterations=100)
LightGBM.fit!(model, X_train, y_train, verbosity = -1) # fit once, without weights
yhat = LightGBM.predict(model, X_test, verbosity = -1)


weights_train = Float32.(weights[train])
model_weights = LightGBM.LGBMClassification(objective="binary", num_class=1, num_iterations=100)#the below works if we just used model again but wanted to make sure we're not overriding anything
LightGBM.fit!(model_weights, X_train, y_train; weights=weights_train, verbosity = -1) # fit again with weights
yhat_with_weights = LightGBM.predict(model_weights, X_test, verbosity = -1)


@test yhat_with_weights != yhat # All we can really say about fitting with/without weights for this example is that the solutions shouldn't be identical
```

**Comment by yalwan-iqvia** [comment]
When we make a new release (soon-ish) with 3.1 pre-bundled, we should probably revisit this in conjunction with upgraded MLJ libs and see if the problem disappears or not.

**Comment by kd-iqvia** [comment]
Seems like the issue still exists. I checked that by reverting this line https://github.com/IQVIA-ML/LightGBM.jl/blob/master/test/mlj/binary_classifier.jl#L19 back to using `rand(1000)` instead of `rand(1010)` and it triggered the same error on https://github.com/IQVIA-ML/LightGBM.jl/blob/master/test/mlj/binary_classifier.jl#L40. Need to investigate.

**Comment by kainkad** [comment]
This issue can be closed. There were few modifications to the binary_classifier test since then (#119) but I have tested locally with the initial `Nsamples`  of `rand(1000)` that was triggering the error and it seems to be working now. I'm happy with the status quo on the binary_classifier so no need to restore to the initial  `Nsamples`.
