### ISSUE TITLE
Add "alpha" parameter used for Huber loss and Quantile regression

### ISSUE THREAD

**Issue by rbeeli** [IQVIA-ML/LightGBM.jl#89]
Is it possible to specify the `alpha` parameter somehow already? If not, could this parameter be added?

LightGBM docs:
```
alpha, default = 0.9, type = double, constraints: alpha > 0.0
  used only in huber and quantile regression applications
  parameter for Huber loss and Quantile regression
```

[https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric-parameters](https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric-parameters)

**Comment by yalwan-iqvia** [comment]
Hi @rbeeli thanks for raising the issue. This one is fairly straightforward and we can probably have a patch release with this fairly soon. We'll keep you up to date.
